@startuml

actor Enseignant as ENS
actor :Admin Centre rsrc: as ADMIN
actor :Support FENS: as FENS
actor :Etudiant ISIS: as ETUD
actor :Etudiant testeur: as ETUD_TEST
actor :Etudiant autorisé: as ETUD_AUTORISE
actor UNIT

ETUD_TEST --|> ETUD
ETUD_AUTORISE --|> ETUD
FENS --|> ADMIN

(Prévoir rsrc) as (PREVOIR)
(Créer rsrc) as (CREER)
(Tester rsrc) as (TESTER)
(Publier rsrc) as (PUBLIER)
(Faire connaître rsrc) as (FAIRE_CONNAITRE)
(Modifier rsrc) as (MODIFIER)
(Administrer rsrc) as (ADMINISTRER)
(Accéder rsrc) as (ACCEDER)
(Evaluer rsrc) as (EVALUER)

(PREVOIR) -- ENS
(PREVOIR) -- FENS
(CREER) -- ENS
(CREER) -- FENS
(TESTER) -- ENS
(TESTER) -- FENS
(TESTER) -- ETUD_TEST
(PUBLIER) -- ENS
(PUBLIER) -- FENS
(PUBLIER) -- UNIT
(FAIRE_CONNAITRE) -- ENS
(FAIRE_CONNAITRE) -- FENS
(MODIFIER) -- ENS
(MODIFIER) -- FENS
(MODIFIER) -- ADMIN
(ADMINISTRER) -- ENS
(ADMINISTRER) -- FENS
(ADMINISTRER) -- ADMIN
(ACCEDER) -- ETUD_AUTORISE



@enduml